name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 时间 00:00 运行（可修改）
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main  # 当 main 分支更新时触发

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 生成 Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: xyz349925756
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Shanghai  # 设置时区
