name: GitHub Streak

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 00:00 更新
  workflow_dispatch:  # 允许手动运行

jobs:
  update-streak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Fetch Streak Stats
        run: |
          curl -o streak-stats.svg "https://streak-stats.demolab.com/?user=xyz349925756&theme=default"


      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add streak-stats.svg
          git commit -m "Update Streak Stats" || echo "No changes to commit"
          git push
